export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_ALL_PRODUCTS = 'REMOVE_ALL_PRODUCTS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const INCREMENT = 'INCREMENT';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const RECEIVED_PRODUCTS = 'RECEIVED_PRODUCTS';
export const RECEIVED_ERROR = 'RECEIVED_ERROR';

export const DECREMENT = 'DECREMENT';
export const DECREMENT_OK = 'DECREMENT_OK';
export const DECREMENT_FAILED = 'DECREMENT_FAILED';

